# Generated by Django 3.2.25 on 2025-05-06 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseLianjia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='区域')),
                ('layout', models.CharField(blank=True, max_length=20, null=True, verbose_name='户型')),
                ('area', models.CharField(blank=True, max_length=20, null=True, verbose_name='面积')),
                ('direction', models.CharField(blank=True, max_length=20, null=True, verbose_name='朝向')),
                ('decoration', models.CharField(blank=True, max_length=20, null=True, verbose_name='装修情况')),
                ('floor', models.CharField(blank=True, max_length=50, null=True, verbose_name='楼层')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('follow_info', models.CharField(blank=True, max_length=50, null=True, verbose_name='关注信息')),
                ('tags', models.TextField(blank=True, null=True, verbose_name='标签')),
                ('link', models.CharField(max_length=255, unique=True, verbose_name='详情链接')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '链家房源',
                'verbose_name_plural': '链家房源',
                'db_table': 'houses_lianjia',
                'ordering': ['-created_at'],
            },
        ),
    ]
